version: '3.5'

services:
  front:
    build: './frontend'
    ports:
      - 5000:5000
    container_name: front
  back:
    build: './backend'
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/usr/src/app/logs.txt
    container_name: back
