version: '3.5'

services:
  backend:
    image: back
    build: .
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=pass
      - DB_HOST=db
    container_name: back
  frontend:
    image: front
    build: .
    ports:
      - 5000:5000
    container_name: front
    environment:
      - API_URL=/api/
  redis:
    image: redis
    build: .
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    
    container_name: redis-backend
  db:
    image: postgres
    build: .
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./database:/var/lib/postgresql/data
    container_name: db_postgres
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
 database:
 data:
