version: '3.5'

services:
  backend:
    image: ml_backend
    build: .
    ports:
      - 5000:5000
    depends_on:
      - training
    volumes:
      - model:/src/model
    container_name: backend

  frontend: 
    image: ml_frontend
    build: .
    ports:
      - 3000:3000
    container_name: frontend

  training:
    image: ml_training
    build: .
    volumes:
      - model:/src/model
      - imgs:/src/imgs
      - data:/src/data
    container_name: training

volumes:
  model:
  imgs:
  data:
