version: '3.5'

services:
  backend:
    image: back
    build: .
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
    container_name: back
  frontend:
    image: front
    build: .
    ports:
      - 5000:5000
    container_name: front
  redis:
    image: redis
    build: .
    ports:
      - 6379:6379
    container_name: redis-backend
